package:
  name: bioat
  version: "0.12.13"

source:
  git_url: https://github.com/hermanzhaozzzz/bioat
  git_rev: v0.12.13

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  build:
    - python
    - pip

  run:
    - python >=3.7

test:
  commands:
    - bioat --help

about:
  home: https://github.com/hermanzhaozzzz/bioat
  license: MIT
  summary: "A bioinformatics analysis toolkit"
