package:
  name: bioat
  version: "0.12.13"

source:
  git_url: https://github.com/hermanzhaozzzz/bioat
  git_rev: v0.12.13

build:
  noarch: python  # 使用 noarch: python 来表示该包与平台无关
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - python
    - pip
    - setuptools  # 明确指定 setuptools 作为构建后端
    - poetry  # poetry 作为 host 依赖
  run:
    - python

test:
  commands:
    - bioat --help

about:
  home: https://github.com/hermanzhaozzzz/bioat
  license: AGPL-3.0-only  # 更新为 GNU AGPLv3
  license_file: LICENSE
  summary: "A bioinformatics analysis toolkit"

extra:
  recipe-maintainers:
    - hermanzhaozzzz
