package:
  name: bioat
  version: "0.12.13"

source:
  git_url: https://github.com/hermanzhaozzzz/bioat
  git_rev: v0.12.13

build:
  noarch: python  # 使用 noarch: python 来表示该包与平台无关
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - python >=3.8  # 在 host 中指定 Python 版本下限
    - pip
    - setuptools  # 明确指定 setuptools 作为构建后端
    - poetry
  run:
    - python >=3.8  # 在 run 中也指定 Python 版本下限

test:
  commands:
    - bioat --help

about:
  home: https://github.com/hermanzhaozzzz/bioat
  license: AGPL-3.0-only  # 更新为 GNU AGPLv3
  license_file: 
  summary: "bioat, A python package & command line toolkit for Bioinformatics and data science!"

extra:
  recipe-maintainers:
    - hermanzhaozzzz
